// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: order_manage/order_manage.proto

package order_manage

import (
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderId) Reset() {
	*x = OrderId{}
	mi := &file_order_manage_order_manage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderId) ProtoMessage() {}

func (x *OrderId) ProtoReflect() protoreflect.Message {
	mi := &file_order_manage_order_manage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderId.ProtoReflect.Descriptor instead.
func (*OrderId) Descriptor() ([]byte, []int) {
	return file_order_manage_order_manage_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Items         []string               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Price         float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Destination   string                 `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_manage_order_manage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_manage_order_manage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_manage_order_manage_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Order) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type CombinedShipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrdersList    []*Order               `protobuf:"bytes,3,rep,name=ordersList,proto3" json:"ordersList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedShipment) Reset() {
	*x = CombinedShipment{}
	mi := &file_order_manage_order_manage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedShipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedShipment) ProtoMessage() {}

func (x *CombinedShipment) ProtoReflect() protoreflect.Message {
	mi := &file_order_manage_order_manage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedShipment.ProtoReflect.Descriptor instead.
func (*CombinedShipment) Descriptor() ([]byte, []int) {
	return file_order_manage_order_manage_proto_rawDescGZIP(), []int{2}
}

func (x *CombinedShipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CombinedShipment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CombinedShipment) GetOrdersList() []*Order {
	if x != nil {
		return x.OrdersList
	}
	return nil
}

var File_order_manage_order_manage_proto protoreflect.FileDescriptor

const file_order_manage_order_manage_proto_rawDesc = "" +
	"\n" +
	"\x1forder_manage/order_manage.proto\x12\tecommerce\x1a\x1egoogle/protobuf/wrappers.proto\"\t\n" +
	"\aOrderId\"y\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05items\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12 \n" +
	"\vdestination\x18\x05 \x01(\tR\vdestination\"l\n" +
	"\x10CombinedShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x120\n" +
	"\n" +
	"ordersList\x18\x03 \x03(\v2\x10.ecommerce.OrderR\n" +
	"ordersList2\x9d\x02\n" +
	"\vOrderManage\x12:\n" +
	"\bgetOrder\x12\x1c.google.protobuf.StringValue\x1a\x10.ecommerce.Order\x12@\n" +
	"\fsearchOrders\x12\x1c.google.protobuf.StringValue\x1a\x10.ecommerce.Order0\x01\x12@\n" +
	"\fupdateOrders\x12\x10.ecommerce.Order\x1a\x1c.google.protobuf.StringValue(\x01\x12N\n" +
	"\rprocessOrders\x12\x1c.google.protobuf.StringValue\x1a\x1b.ecommerce.CombinedShipment(\x010\x01B\x1bZ\x19order_manage/order_manageb\x06proto3"

var (
	file_order_manage_order_manage_proto_rawDescOnce sync.Once
	file_order_manage_order_manage_proto_rawDescData []byte
)

func file_order_manage_order_manage_proto_rawDescGZIP() []byte {
	file_order_manage_order_manage_proto_rawDescOnce.Do(func() {
		file_order_manage_order_manage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_manage_order_manage_proto_rawDesc), len(file_order_manage_order_manage_proto_rawDesc)))
	})
	return file_order_manage_order_manage_proto_rawDescData
}

var file_order_manage_order_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_manage_order_manage_proto_goTypes = []any{
	(*OrderId)(nil),              // 0: ecommerce.OrderId
	(*Order)(nil),                // 1: ecommerce.Order
	(*CombinedShipment)(nil),     // 2: ecommerce.CombinedShipment
	(*wrappers.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_order_manage_order_manage_proto_depIdxs = []int32{
	1, // 0: ecommerce.CombinedShipment.ordersList:type_name -> ecommerce.Order
	3, // 1: ecommerce.OrderManage.getOrder:input_type -> google.protobuf.StringValue
	3, // 2: ecommerce.OrderManage.searchOrders:input_type -> google.protobuf.StringValue
	1, // 3: ecommerce.OrderManage.updateOrders:input_type -> ecommerce.Order
	3, // 4: ecommerce.OrderManage.processOrders:input_type -> google.protobuf.StringValue
	1, // 5: ecommerce.OrderManage.getOrder:output_type -> ecommerce.Order
	1, // 6: ecommerce.OrderManage.searchOrders:output_type -> ecommerce.Order
	3, // 7: ecommerce.OrderManage.updateOrders:output_type -> google.protobuf.StringValue
	2, // 8: ecommerce.OrderManage.processOrders:output_type -> ecommerce.CombinedShipment
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_manage_order_manage_proto_init() }
func file_order_manage_order_manage_proto_init() {
	if File_order_manage_order_manage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_manage_order_manage_proto_rawDesc), len(file_order_manage_order_manage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_manage_order_manage_proto_goTypes,
		DependencyIndexes: file_order_manage_order_manage_proto_depIdxs,
		MessageInfos:      file_order_manage_order_manage_proto_msgTypes,
	}.Build()
	File_order_manage_order_manage_proto = out.File
	file_order_manage_order_manage_proto_goTypes = nil
	file_order_manage_order_manage_proto_depIdxs = nil
}
