// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: order_manage/order_manage.proto

package order_manage

import (
	context "context"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderManage_GetOrder_FullMethodName      = "/ecommerce.OrderManage/getOrder"
	OrderManage_SearchOrders_FullMethodName  = "/ecommerce.OrderManage/searchOrders"
	OrderManage_UpdateOrders_FullMethodName  = "/ecommerce.OrderManage/updateOrders"
	OrderManage_ProcessOrders_FullMethodName = "/ecommerce.OrderManage/processOrders"
)

// OrderManageClient is the client API for OrderManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderManageClient interface {
	GetOrder(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Order, error)
	SearchOrders(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error)
	UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Order, wrappers.StringValue], error)
	ProcessOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[wrappers.StringValue, CombinedShipment], error)
}

type orderManageClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderManageClient(cc grpc.ClientConnInterface) OrderManageClient {
	return &orderManageClient{cc}
}

func (c *orderManageClient) GetOrder(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, OrderManage_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManageClient) SearchOrders(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Order], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderManage_ServiceDesc.Streams[0], OrderManage_SearchOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[wrappers.StringValue, Order]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderManage_SearchOrdersClient = grpc.ServerStreamingClient[Order]

func (c *orderManageClient) UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Order, wrappers.StringValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderManage_ServiceDesc.Streams[1], OrderManage_UpdateOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Order, wrappers.StringValue]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderManage_UpdateOrdersClient = grpc.ClientStreamingClient[Order, wrappers.StringValue]

func (c *orderManageClient) ProcessOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[wrappers.StringValue, CombinedShipment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderManage_ServiceDesc.Streams[2], OrderManage_ProcessOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[wrappers.StringValue, CombinedShipment]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderManage_ProcessOrdersClient = grpc.BidiStreamingClient[wrappers.StringValue, CombinedShipment]

// OrderManageServer is the server API for OrderManage service.
// All implementations must embed UnimplementedOrderManageServer
// for forward compatibility.
type OrderManageServer interface {
	GetOrder(context.Context, *wrappers.StringValue) (*Order, error)
	SearchOrders(*wrappers.StringValue, grpc.ServerStreamingServer[Order]) error
	UpdateOrders(grpc.ClientStreamingServer[Order, wrappers.StringValue]) error
	ProcessOrders(grpc.BidiStreamingServer[wrappers.StringValue, CombinedShipment]) error
	mustEmbedUnimplementedOrderManageServer()
}

// UnimplementedOrderManageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderManageServer struct{}

func (UnimplementedOrderManageServer) GetOrder(context.Context, *wrappers.StringValue) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderManageServer) SearchOrders(*wrappers.StringValue, grpc.ServerStreamingServer[Order]) error {
	return status.Errorf(codes.Unimplemented, "method SearchOrders not implemented")
}
func (UnimplementedOrderManageServer) UpdateOrders(grpc.ClientStreamingServer[Order, wrappers.StringValue]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateOrders not implemented")
}
func (UnimplementedOrderManageServer) ProcessOrders(grpc.BidiStreamingServer[wrappers.StringValue, CombinedShipment]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessOrders not implemented")
}
func (UnimplementedOrderManageServer) mustEmbedUnimplementedOrderManageServer() {}
func (UnimplementedOrderManageServer) testEmbeddedByValue()                     {}

// UnsafeOrderManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderManageServer will
// result in compilation errors.
type UnsafeOrderManageServer interface {
	mustEmbedUnimplementedOrderManageServer()
}

func RegisterOrderManageServer(s grpc.ServiceRegistrar, srv OrderManageServer) {
	// If the following call pancis, it indicates UnimplementedOrderManageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderManage_ServiceDesc, srv)
}

func _OrderManage_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManageServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderManage_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManageServer).GetOrder(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManage_SearchOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrappers.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderManageServer).SearchOrders(m, &grpc.GenericServerStream[wrappers.StringValue, Order]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderManage_SearchOrdersServer = grpc.ServerStreamingServer[Order]

func _OrderManage_UpdateOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderManageServer).UpdateOrders(&grpc.GenericServerStream[Order, wrappers.StringValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderManage_UpdateOrdersServer = grpc.ClientStreamingServer[Order, wrappers.StringValue]

func _OrderManage_ProcessOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderManageServer).ProcessOrders(&grpc.GenericServerStream[wrappers.StringValue, CombinedShipment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderManage_ProcessOrdersServer = grpc.BidiStreamingServer[wrappers.StringValue, CombinedShipment]

// OrderManage_ServiceDesc is the grpc.ServiceDesc for OrderManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.OrderManage",
	HandlerType: (*OrderManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getOrder",
			Handler:    _OrderManage_GetOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "searchOrders",
			Handler:       _OrderManage_SearchOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "updateOrders",
			Handler:       _OrderManage_UpdateOrders_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "processOrders",
			Handler:       _OrderManage_ProcessOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "order_manage/order_manage.proto",
}
